kind: pipeline
type: docker
name: docker_container
   
steps:
- name: Base Platform
  image: mcr.microsoft.com/azure-cli
  commands:
  - pip install --upgrade pip
  - pip install azure-identity
  - pip install azure-mgmt-datafactory
  - cp -r /drone/src /pyscript/
  - cd pyscript
  - python adtest.py
